# Kubernetes deployment configuration for production
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sortyx-backend
  labels:
    app: sortyx-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sortyx-backend
  template:
    metadata:
      labels:
        app: sortyx-backend
    spec:
      containers:
      - name: sortyx-backend
        image: gcr.io/PROJECT_ID/sortyx-backend:latest
        ports:
        - containerPort: 8000
        env:
        - name: ENVIRONMENT
          value: "production"
        - name: GEMINI_API_KEY
          valueFrom:
            secretKeyRef:
              name: sortyx-secrets
              key: gemini-api-key
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sortyx-secrets
              key: db-password
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: sortyx-backend-service
spec:
  selector:
    app: sortyx-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer